language: node_js

node_js:
  - "0.10"

services:
  - mongodb # Start MongoDB in TravisCI before building

before_install: 
  - npm install -g grunt-cli

install:
  - npm install

before_script:
  - grunt jshint
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 15 # give server and MongoDB time to start

script:
  - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots,coverage,coveralls --browsers=Firefox
  - node_modules/.bin/protractor e2e-tests/protractor.conf.js --browser=firefox
  - grunt compress

deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIPSF2BGQDMLQL23Q
  secret_access_key:
  secure: "WM45i/WyRRHtU4Qprkd89UQdJcdgegsIbURK+8LNAKPcLBGJDnagDwloFTR0POpNSr7ST5b5TBSrDimoNSViE08BU7wz253Oa0TipIMor7xb8McR7doloRdprqJ0ssP3uST69bytM1Z/dXWvTR4oTljSVUKB6oyRGx2ql3RjvSucELvBkAKYn6F1UfMMkJxxb/J6vgX6sSlHPcO4ciY//CwWY+GLRcs2TX6FEwfIrCdvFDt19NPkieaTQrv39lopIcFzDLv2z1pCaa5zspHpUmLqRsvlerKcffGoWmzBsX4Z/hHZpfhhKi4KDP/Acdaky/H5CfEYvFnSTzTRf3xwX5dlawiD0C+c/bGCVQEPeGB65UPcN8REukI1rMfMCAQASsOqWVpB4tSiT+A+GNO/9gEnTubpWf/52zD7o90n/UsXnKo9en8hVNADZSWo5nEDIc3OOnLxAo2mzTvRQjzI09FzvK7bhQxI0Y+y+gAfLBWQVQQnP8iCQEKVuPSf8W0G9Ce7nUoIhZ99yd2PPtYy3R98Oqz2HVGmlgFyKOFhyvE32J27m4xFF3+cBDBq8Aw/q1iebYAFwdDLxHeAOHR4If4nVjMwcsGR3TXlcQBt7UQMgcnUyFY3OMhrmOaImwrDJfUOpoSPbFxFGssAcFU1ZHv7Zyy3u+/edohEZ/PbNw4="
  region: eu-west-1
  app: lab-protocols
  env: labProtocols-env
  bucket_name: elasticbeanstalk-eu-west-1-502514754647
  skip_cleanup: true
  zip_file: production.zip
  on:
    branch: master